### 용어 풀이 - 라인에서 쓰는 말

| 말 | 뜻 |
|---|---|
| 웨이퍼 | 반도체를 만드는 얇은 원판. 이 위에 회로를 층층이 쌓아 올린다 |
| 챔버 | 공정이 실제로 일어나는 밀폐된 방. 이 안에 웨이퍼를 넣고 가스를 넣거나 깎는다 |
| 챔버온도 | 그 방 안의 온도. 너무 높거나 낮으면 깎이는 정도, 쌓이는 두께가 달라진다 |
| 압력 | 챔버 안의 기압. 가스가 얼마나 촘촘히 차 있는지를 나타낸다 |
| 설비명 | 그 일을 한 장비의 이름. ETCH는 깎는 장비, CVD/PVD는 얇게 입히는 장비 |
| 양품 / 불량 | 검사를 통과한 것 / 통과하지 못한 것. 판정은 공정이 다 끝난 뒤에 붙는다 |
| 결측 (빈칸) | 값이 기록되지 않은 칸. 센서가 잠깐 꺼졌거나 기록이 누락된 자리 |

### Q1. 딕셔너리로 표 만들기
앞사람이 남긴 표를 그대로 되살린다.

In [2]:
# 표를 다루는 도구를 pd라는 짧은 이름으로 불러온다
import pandas as pd

# 열 이름을 열쇠로, 값 목록을 값으로 갖는 딕셔너리
data = {
    "설비명": ["ETCH-01", "ETCH-01", "CVD-01", "CVD-01", "PVD-01", "PVD-01"],
    "챔버온도": [250.1, 248.7, 251.3, 262.9, 249.8, 250.4],
    "압력": [99.2, 101.5, None, 97.3, 100.1, 99.8],
    "양품여부": ["양품", "양품", "불량", "양품", "양품", "불량"],
}

# 딕셔너리를 표로 바꾼다
df = pd.DataFrame(data)

# 만든 표를 화면에 보여준다
df

       설비명   챔버온도     압력 양품여부
0  ETCH-01  250.1   99.2   양품
1  ETCH-01  248.7  101.5   양품
2   CVD-01  251.3    NaN   불량
3   CVD-01  262.9   97.3   양품
4   PVD-01  249.8  100.1   양품
5   PVD-01  250.4   99.8   불량

### Q2. 표의 크기 확인
몇 줄짜리 기록을 넘겨받은 건지 확인한다.

In [14]:
# (행 개수, 열 개수) 형태로 나온다
df.shape

(6, 4)

### Q3. 앞부분만 보기
전체를 다 띄우지 않고 위에서 3줄만 확인한다.

In [4]:
# 괄호 안 숫자만큼 위에서부터 보여준다
df.head(3)

       설비명   챔버온도     압력 양품여부
0  ETCH-01  250.1   99.2   양품
1  ETCH-01  248.7  101.5   양품
2   CVD-01  251.3    NaN   불량

### Q4. 정렬하기
챔버온도가 높은 순으로 줄을 다시 늘어놓는다. 제일 뜨거웠던 기록이 맨 위로 온다.

In [5]:
# ascending=False — 큰 값이 위로 오게(내림차순)
df.sort_values("챔버온도", ascending=False)

       설비명   챔버온도     압력 양품여부
3   CVD-01  262.9   97.3   양품
2   CVD-01  251.3    NaN   불량
5   PVD-01  250.4   99.8   불량
0  ETCH-01  250.1   99.2   양품
4   PVD-01  249.8  100.1   양품
1  ETCH-01  248.7  101.5   양품

### Q5. 값 종류별로 세기
양품이 몇 건, 불량이 몇 건인지 센다.

In [6]:
# 값 종류별 개수를 많은 순으로 세어준다
df["양품여부"].value_counts()

양품여부
양품    4
불량    2
Name: count, dtype: int64

### Q6. 조건에 맞는 행만 고르기
챔버온도가 255보다 높았던 기록만 남긴다.

In [7]:
# 대괄호 안에 조건식을 넣으면 조건이 참인 행만 남는다
df[df["챔버온도"] > 255]

      설비명   챔버온도    압력 양품여부
3  CVD-01  262.9  97.3   양품

### Q7. 빈칸 세기
기록이 빠진 칸이 열마다 몇 개인지 센다.

In [8]:
# 각 칸이 비었는지를 참/거짓으로 표시한 뒤
# sum으로 참인 것의 개수를 열마다 센다
df.isnull().sum()

설비명     0
챔버온도    0
압력      1
양품여부    0
dtype: int64

### Q8. 평균과 흩어진 정도
챔버온도가 평소 어디쯤이고, 얼마나 들쭉날쭉한지 본다.

In [9]:
# 평균 — 값들을 다 더해 개수로 나눈 것
print("평균:", df["챔버온도"].mean())

# 표준편차 — 값들이 평균에서 얼마나 흩어져 있는지
print("표준편차:", df["챔버온도"].std())

평균: 252.20000000000002
표준편차: 5.309613921934428

### Q9. 그룹으로 묶어 계산하기
장비별로 묶어서 챔버온도 평균을 구한다. 어느 장비가 유독 뜨거운지 보인다.

In [10]:
# 설비명이 같은 것끼리 묶은 뒤, 챔버온도의 평균을 낸다
df.groupby("설비명")["챔버온도"].mean()

설비명
CVD-01     257.1
ETCH-01    249.4
PVD-01     250.1
Name: 챔버온도, dtype: float64

### Q10. 파일로 저장하기
복원한 표를 파일로 남긴다. 다음 사람은 커피 자국 없는 걸 받게 된다.

In [11]:
# index=False — 왼쪽 줄번호는 저장하지 않는다
# encoding="utf-8-sig" — 엑셀에서 열어도 한글이 안 깨지게
df.to_csv("연습표.csv", index=False, encoding="utf-8-sig")

---
## 직접 해보기 (도전) - 숫자가 하나 사라진다

- 상황: 압력을 기준으로 둘로 나눠 세었는데 합이 전체와 다르다
- 할 일: 왜 그런지 밝히고, 빠진 행을 찾아낸다
- 결과물: 이유 한 줄 + 빠진 행이 출력되는 코드

In [12]:
# 전체 줄 수
print("전체:", len(df))

# 압력이 99보다 큰 행
print("99 초과:", len(df[df["압력"] > 99]))

# 압력이 99 이하인 행
print("99 이하:", len(df[df["압력"] <= 99]))

# 두 개를 더하면?
print("합:", len(df[df["압력"] > 99]) + len(df[df["압력"] <= 99]))

전체: 6
99 초과: 4
99 이하: 1
합: 5

압력에 결측치 존재

In [15]:
# 압력이 비어 있는 행만 고르기
df[df['압력'].isna()]

      설비명   챔버온도  압력 양품여부
2  CVD-01  251.3 NaN   불량

### 문법 노트 - 비교 조건과 빈칸

| 알게 된 것 | 내용 |
|---|---|
| 빈칸은 어느 쪽에도 안 잡힌다 | 빈칸은 `> 99`도 `<= 99`도 참이 되지 않아 양쪽에서 모두 빠진다 |
| 그래서 합이 안 맞는다 | 조건으로 나눈 결과를 더했을 때 전체보다 적으면, 그 차이가 빈칸 개수 |
| 확인하는 법 | 거른 결과의 합과 전체 줄 수를 대조한다 |